/* Autogenerated code by MGen for JavaScript */

/*jshint -W069 */ // Turn of lint warnings for accessing a property using a string literal with square bracket notation.
(function(){
	"use strict";
	var blueprint = {};
	
	blueprint.classes = {};
	blueprint.classes["battleship.messages.Chat"] =  {
		"__t": "Q+M",
		"text": {
			"flags": [],
			"type": "string",
			"hash": "wzw"
		}
	};
	blueprint.classes["battleship.messages.Fire"] =  {
		"__t": "nKY",
		"position": {
			"flags": [],
			"type": "battleship.state.Vec2",
			"hash": "mR8"
		}
	};
	blueprint.classes["battleship.messages.PhaseChange"] =  {
		"__t": "3mc",
		"phase": {
			"flags": [],
			"type": "enum:LOBBY, PLAYING, PAUSED",
			"hash": "Hck"
		}
	};
	blueprint.classes["battleship.messages.Snapshot"] =  {
		"__t": "19I",
		"state": {
			"flags": [],
			"type": "battleship.state.Game",
			"hash": "Phk"
		}
	};
	blueprint.classes["battleship.state.Ship"] =  {
		"__t": "bkI",
		"points": {
			"flags": [],
			"type": "list:battleship.state.Segment",
			"hash": "lw8"
		},
		"team": {
			"flags": [],
			"type": "enum:RED, BLUE, OBSERVERS",
			"hash": "+c8"
		}
	};
	blueprint.classes["battleship.state.Segment"] =  {
		"__t": "LqM",
		"alive": {
			"flags": [],
			"type": "boolean",
			"hash": "L2c"
		},
		"pos": {
			"flags": [],
			"type": "battleship.state.Vec2",
			"hash": "QXQ"
		}
	};
	blueprint.classes["battleship.state.Map"] =  {
		"__t": "E6w",
		"ships": {
			"flags": [],
			"type": "list:battleship.state.Ship",
			"hash": "fR4"
		},
		"size": {
			"flags": [],
			"type": "battleship.state.Vec2",
			"hash": "gwI"
		}
	};
	blueprint.classes["battleship.state.Player"] =  {
		"__t": "th0",
		"team": {
			"flags": [],
			"type": "enum:RED, BLUE, OBSERVERS",
			"hash": "+c8"
		},
		"name": {
			"flags": [],
			"type": "string",
			"hash": "kmY"
		},
		"ready": {
			"flags": [],
			"type": "boolean",
			"hash": "KZU"
		}
	};
	blueprint.classes["battleship.state.Game"] =  {
		"__t": "r9U",
		"players": {
			"flags": [],
			"type": "list:battleship.state.Player",
			"hash": "c48"
		},
		"map": {
			"flags": [],
			"type": "battleship.state.Map",
			"hash": "Uyo"
		},
		"phase": {
			"flags": [],
			"type": "enum:LOBBY, PLAYING, PAUSED",
			"hash": "Hck"
		},
		"currentTeam": {
			"flags": [],
			"type": "enum:RED, BLUE, OBSERVERS",
			"hash": "xno"
		},
		"timeLastMove": {
			"flags": [],
			"type": "float64",
			"hash": "WGw"
		}
	};
	blueprint.classes["battleship.state.Vec2"] =  {
		"__t": "Fxs",
		"x": {
			"flags": [],
			"type": "int32",
			"hash": "Hm8"
		},
		"y": {
			"flags": [],
			"type": "int32",
			"hash": "Dk4"
		}
	};
	blueprint.lookup = function( typeId )  {
		var t = typeId.match(/(.{1,3})/g); // Split typeId into array for easier reading of inheritance (every 3 char is a type).
		switch( t[0] )  {
			case "Q+M":
				return "battleship.messages.Chat";
			case "nKY":
				return "battleship.messages.Fire";
			case "3mc":
				return "battleship.messages.PhaseChange";
			case "19I":
				return "battleship.messages.Snapshot";
			case "bkI":
				return "battleship.state.Ship";
			case "LqM":
				return "battleship.state.Segment";
			case "E6w":
				return "battleship.state.Map";
			case "th0":
				return "battleship.state.Player";
			case "r9U":
				return "battleship.state.Game";
			case "Fxs":
				return "battleship.state.Vec2";
		}
	};


	// Support for requirejs etc.
	if (typeof define === "function" && define.amd) {
		define("battleship_blueprint", [], function(){
			return blueprint;
		});
	} else {
		// expose blueprint the old fashioned way.
		window.battleship_blueprint = blueprint;
	}
})();
